stages:
  unzip:
    cmd: python3 data_processing/unzip.py
    params:
    - base.zip_file_path
    - unzip.output_path
    outs:
    - datasets
  preprocess:
    cmd: python3 data_processing/preprocess.py
    deps:
    - datasets
    - data_processing/preprocess.py
    params:
    - preprocess.mean
    - preprocess.output_folder
    - preprocess.std
    - preprocess.test_folder
    - preprocess.train_folder
    - preprocess.valid_folder
    outs:
    - processed_data
  evaluate:
    cmd: python3 data_processing/evaluate.py
    deps:
    - datasets
    - processed_data
    - data_processing/evaluate.py
    params:
    - evaluate.ORIGINAL_DATASET_PATH
    - evaluate.OUTPUT_PATH
    - evaluate.PROCESSED_DATASET_PATH
    metrics:
    - eval_results/live/metrics.json:
        cache: false
