stages:
  unzip:
    cmd: python3 src/unzip.py
    params:
    - base.zip_file_path
    - unzip.output_path
    outs:
    - dataset
  preprocess:
    cmd: python3 src/preprocess.py
    deps:
    - dataset
    - src/preprocess.py
    params:
    - preprocess.mean
    - preprocess.output_folder
    - preprocess.std
    - preprocess.test_folder
    - preprocess.train_folder
    - preprocess.valid_folder
    outs:
    - processed_data
  evaluate:
    cmd: python3 src/evaluate.py
    deps:
    - dataset
    - processed_data
    - src/evaluate.py
    params:
    - evaluate.ORIGINAL_DATASET_PATH
    - evaluate.OUTPUT_PATH
    - evaluate.PROCESSED_DATASET_PATH
    metrics:
    - eval_results/live/matching.json:
        cache: false
