base:
  zip_file_path: "datasets.zip"

unzip:
  input_path: "datasets.zip"
  output_path: "datasets"

preprocess:
  train_folder: "datasets/train"
  test_folder: "datasets/test"
  valid_folder: "datasets/valid"

  output_folder: "processed_data"

  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

evaluate:
  ORIGINAL_DATASET_PATH: "datasets"
  PROCESSED_DATASET_PATH: "processed_data"

  OUTPUT_PATH: "eval_results"
  
  